"""Train continuous SAC with hidden disturbances for the safe evaporator."""
from __future__ import annotations

import argparse
import copy
import csv
from dataclasses import replace
import json
from pathlib import Path
import time

import numpy as np

from .config import ExperimentConfig
from .control import SafeController, build_safety_design, point_in_convex_polygon
from .model import EvaporatorModel
from .plot import (
    close_all_plots,
    plot_disturbance_response,
    plot_disturbances,
    plot_economic_performance,
    plot_empirical_regret,
    plot_feedback_components,
    plot_learning,
    plot_paper_aligned_set_comparison,
    plot_rl_comparison,
    plot_rollout,
    plot_sac_policy_map,
    plot_sets,
    plot_theta_learning,
)
from .sac import ReplayBuffer, SACAgent, SACConfig, set_seed
from .theta_learning import OnlineThetaLearner


OBS_DIM = 17
ACTION_DIM = 2


class ZeroResidualPolicy:
    """No-RL ablation: retain H-infinity/RPI/QP and set SAC residual to zero."""

    alpha = 0.0

    @staticmethod
    def select_action(obs: np.ndarray, deterministic: bool = True) -> np.ndarray:
        del obs, deterministic
        return np.zeros(ACTION_DIM, dtype=np.float32)


def observation(
    model: EvaporatorModel,
    controller: SafeController,
    state: np.ndarray,
    previous_u: np.ndarray,
) -> np.ndarray:
    """Plant feedback plus known controller context; disturbance stays hidden.

    The slow theta/K learner changes the closed-loop transition kernel during
    training.  Supplying its normalized current values prevents replay from
    aliasing transitions generated by different controllers as the same SAC
    state.  These are internal controller parameters, not plant disturbances.
    """
    x = model.normalized_state(state)
    e = x - controller.z
    design = controller.d
    k_scale = np.array([[12.0, 3.0], [1.0, 3.0]], dtype=float)
    parameter_clip = max(float(model.cfg.theta_parameter_clip), 1e-12)
    angle_limit = max(
        np.deg2rad(float(model.cfg.theta_m_max_angle_degrees)), 1e-12
    )
    controller_context = np.concatenate([
        design.k.ravel() / k_scale.ravel(),
        design.theta_h / parameter_clip,
        design.theta_p / parameter_clip,
        [design.theta_m_angle / angle_limit],
    ])
    return np.clip(
        np.concatenate([
            x - controller.d.z_ref,
            e,
            previous_u - controller.d.v_ref,
            controller_context,
        ]),
        -4.0,
        4.0,
    ).astype(np.float32)


def sample_disturbance(cfg: ExperimentConfig, rng: np.random.Generator) -> np.ndarray:
    """Draw the four bounded feed/temperature disturbances from the paper."""
    return rng.uniform(
        cfg.disturbance_nominal - cfg.disturbance_half_range,
        cfg.disturbance_nominal + cfg.disturbance_half_range,
    )


def run_episode(
    cfg: ExperimentConfig,
    model: EvaporatorModel,
    controller: SafeController,
    agent,
    replay: ReplayBuffer,
    rng: np.random.Generator,
    *,
    training: bool,
    global_step: int,
    theta_learner: OnlineThetaLearner | None = None,
) -> tuple[dict[str, float], list[dict[str, object]], int]:
    initial_fraction = (
        cfg.training_initial_radius_fraction
        if training else cfg.evaluation_initial_radius_fraction
    )
    initial_lower = controller.d.z_ref + initial_fraction * (
        controller.d.invariant_lower - controller.d.z_ref
    )
    initial_upper = controller.d.z_ref + initial_fraction * (
        controller.d.invariant_upper - controller.d.z_ref
    )
    if cfg.reset_within_disturbance_identification_window:
        identified_lower = model.normalized_state(
            cfg.safe_center_state - cfg.theta_initial_safe_state_half_range
        )
        identified_upper = model.normalized_state(
            cfg.safe_center_state + cfg.theta_initial_safe_state_half_range
        )
        initial_lower = np.maximum(initial_lower, identified_lower)
        initial_upper = np.minimum(initial_upper, identified_upper)
        if np.any(initial_upper <= initial_lower):
            raise RuntimeError(
                "Disturbance-identified reset window does not intersect the "
                "controlled-invariant set."
            )
    def reset_segment():
        z0 = rng.uniform(initial_lower, initial_upper)
        if training and rng.random() < cfg.training_boundary_start_probability:
            boundary_axis = int(rng.integers(0, 2))
            z0[boundary_axis] = rng.choice([
                initial_lower[boundary_axis], initial_upper[boundary_axis]
            ])
        segment_state = model.physical_state(z0)
        controller.reset(segment_state)
        segment_previous_u = controller.d.v_ref.copy()
        segment_previous_residual = np.zeros(ACTION_DIM, dtype=float)
        segment_disturbance = sample_disturbance(cfg, rng)
        segment_obs = observation(
            model, controller, segment_state, segment_previous_u
        )
        return (
            segment_state,
            segment_previous_u,
            segment_previous_residual,
            segment_disturbance,
            segment_obs,
        )

    (
        state,
        previous_u,
        previous_applied_residual,
        disturbance,
        obs,
    ) = reset_segment()
    reward_reference_cost = model.economic_cost(
        cfg.linearization_state,
        cfg.linearization_input,
        cfg.disturbance_nominal,
    )

    total_return = 0.0
    violations = 0
    rpi_violations = 0
    bound_exceedances = 0
    interventions = 0
    infeasible = 0
    economic_cost_sum = 0.0
    economic_reward_sum = 0.0
    projection_penalty_sum = 0.0
    mapping_penalty_sum = 0.0
    mapping_activations = 0
    move_penalty_sum = 0.0
    safety_penalty_sum = 0.0
    state_excess_squared_sum = 0.0
    input_excess_squared_sum = 0.0
    rpi_excess_squared_sum = 0.0
    rpi_utilization_peak = 0.0
    records: list[dict[str, object]] = []
    last_losses: dict[str, float] | None = None

    for step in range(cfg.steps_per_episode):
        if training and global_step < cfg.warmup_steps:
            raw_action = rng.uniform(-1.0, 1.0, ACTION_DIM).astype(np.float32)
        else:
            raw_action = agent.select_action(
                obs,
                deterministic=not training,
            ).astype(np.float32)

        # The critic stores the original continuous actor command in [-1,1]^2.
        # The environment maps it to a physical residual before the safety QP.
        residual = cfg.residual_action_scale * raw_action
        control, info = controller.act(state, residual)
        next_state = model.step(state, control, disturbance)
        x_next_n = model.normalized_state(next_state)
        e_next = x_next_n - controller.z
        acl = controller.d.a + controller.d.b @ controller.d.k
        effective_w = e_next - acl @ np.asarray(info["e"])

        state_bad = bool(
            np.any(next_state < cfg.state_lower - 1e-8)
            or np.any(next_state > cfg.state_upper + 1e-8)
        )
        input_bad = bool(
            np.any(control < cfg.input_lower - 1e-8)
            or np.any(control > cfg.input_upper + 1e-8)
        )
        rpi_bad = not point_in_convex_polygon(
            e_next, controller.d.rpi_boundary, tol=1e-8
        )
        bound_bad = not point_in_convex_polygon(
            effective_w, controller.d.w_vertices, tol=1e-8
        )
        violation = state_bad or input_bad
        projection = float(info["projection_gap"])
        mapping_scale = float(info["feasible_action_mapping_scale"])
        mapping_gap = float(info["feasible_action_mapping_gap"])
        applied_residual = np.asarray(info["nominal"]) - np.asarray(info["base"])
        # The ray mapper is now part of the declared action parameterization,
        # so its safe result is the action attributed to SAC.  Only an actual
        # QP fallback suppresses learning credit.
        execution_mask = float(info["qp_feasible"])
        cost = model.economic_cost(next_state, control, disturbance)
        if training and theta_learner is not None:
            theta_learner.observe_transition(
                state, control, next_state, cost, controller.d
            )
        economic_reward = (reward_reference_cost - cost) / cfg.reward_cost_scale
        state_excess = (
            np.maximum(cfg.state_lower - next_state, 0.0)
            + np.maximum(next_state - cfg.state_upper, 0.0)
        ) / cfg.state_scale
        input_excess = (
            np.maximum(cfg.input_lower - control, 0.0)
            + np.maximum(control - cfg.input_upper, 0.0)
        ) / cfg.input_scale
        rpi_ratio = np.where(
            e_next >= 0.0,
            e_next / np.maximum(controller.d.rpi_support_upper, 1e-12),
            -e_next / np.maximum(controller.d.rpi_support_lower, 1e-12),
        )
        rpi_excess = np.maximum(rpi_ratio - 1.0, 0.0)
        state_excess_squared = float(np.sum(state_excess ** 2))
        input_excess_squared = float(np.sum(input_excess ** 2))
        rpi_excess_squared = float(np.sum(rpi_excess ** 2))
        projection_penalty = cfg.projection_penalty_weight * projection ** 2
        mapping_penalty = (
            cfg.feasible_action_mapping_penalty_weight * mapping_gap ** 2
        )
        move_penalty = cfg.input_move_penalty_weight * float(
            np.sum((applied_residual - previous_applied_residual) ** 2)
        )
        safety_penalty = (
            cfg.state_violation_event_penalty * float(state_bad)
            + cfg.input_violation_event_penalty * float(input_bad)
            + cfg.rpi_violation_event_penalty * float(rpi_bad)
            + cfg.qp_infeasible_event_penalty * float(not info["qp_feasible"])
            + cfg.state_excess_square_weight * state_excess_squared
            + cfg.input_excess_square_weight * input_excess_squared
            + cfg.rpi_excess_square_weight * rpi_excess_squared
        )
        reward = (
            economic_reward - projection_penalty - mapping_penalty
            - move_penalty - safety_penalty
        )
        segment_done = bool(
            training
            and int(cfg.training_segment_steps) > 0
            and (step + 1) % int(cfg.training_segment_steps) == 0
        )
        done = bool(step == cfg.steps_per_episode - 1 or segment_done)
        next_disturbance = sample_disturbance(cfg, rng)
        next_obs = observation(
            model,
            controller,
            next_state,
            np.asarray(info["actual_norm"]),
        )

        if training:
            replay.add(
                obs, raw_action, reward, next_obs, done,
                execution_mask=execution_mask,
            )
            # Match the CSTR-SAC warm-up order: random actions are retained
            # until warmup_steps, but learning begins as soon as one complete
            # replay minibatch exists.  The actor is therefore already trained
            # when it first takes control.
            if replay.size >= cfg.batch_size:
                for _ in range(cfg.updates_per_step):
                    last_losses = agent.update(replay, cfg.batch_size)

        violations += int(violation)
        rpi_violations += int(rpi_bad)
        bound_exceedances += int(bound_bad)
        interventions += int(projection > cfg.qp_intervention_tolerance)
        infeasible += int(not info["qp_feasible"])
        economic_cost_sum += cost
        economic_reward_sum += economic_reward
        projection_penalty_sum += projection_penalty
        mapping_penalty_sum += mapping_penalty
        mapping_activations += int(mapping_scale < 1.0 - 1e-10)
        move_penalty_sum += move_penalty
        safety_penalty_sum += safety_penalty
        state_excess_squared_sum += state_excess_squared
        input_excess_squared_sum += input_excess_squared
        rpi_excess_squared_sum += rpi_excess_squared
        rpi_utilization_peak = max(
            rpi_utilization_peak,
            float(np.max(rpi_ratio)),
        )
        total_return += reward
        records.append({
            "time": step * cfg.dt_min,
            "state": state.copy(),
            "control": control.copy(),
            "disturbance": disturbance.copy(),
            "raw_action": raw_action.copy(),
            "residual": residual.copy(),
            "applied_residual": applied_residual.copy(),
            "execution_mask": execution_mask,
            "feasible_action_mapping_scale": mapping_scale,
            "feasible_action_mapping_gap": mapping_gap,
            "base": np.asarray(info["base"]).copy(),
            "nominal_control": np.asarray(info["nominal"]).copy(),
            "ancillary": np.asarray(info["ancillary"]).copy(),
            "reward": reward,
            "economic_cost": cost,
            "economic_reward": economic_reward,
            "projection_penalty": projection_penalty,
            "mapping_penalty": mapping_penalty,
            "move_penalty": move_penalty,
            "safety_penalty": safety_penalty,
            "state_excess_squared": state_excess_squared,
            "input_excess_squared": input_excess_squared,
            "rpi_excess_squared": rpi_excess_squared,
            "violation": violation,
            "rpi_violation": rpi_bad,
            "projection_gap": projection,
            "candidate": np.asarray(info["candidate"]).copy(),
            "nominal": np.asarray(info["nominal"]).copy(),
            "error": e_next.copy(),
            "effective_w": effective_w.copy(),
        })
        if segment_done and step < cfg.steps_per_episode - 1:
            (
                state,
                previous_u,
                previous_applied_residual,
                disturbance,
                obs,
            ) = reset_segment()
        else:
            state = next_state
            obs = next_obs
            disturbance = next_disturbance
            previous_u = np.asarray(info["actual_norm"])
            previous_applied_residual = applied_residual
        global_step += 1

    q_loss = float("nan")
    actor_loss = float("nan")
    entropy = float("nan")
    if last_losses:
        q_loss = 0.5 * (
            float(last_losses["q1_loss"]) + float(last_losses["q2_loss"])
        )
        actor_loss = float(last_losses["actor_loss"])
        entropy = -float(last_losses["mean_logp"])
    stats = {
        "return": total_return,
        "return_per_step": total_return / cfg.steps_per_episode,
        "economic_cost_mean": economic_cost_sum / cfg.steps_per_episode,
        "economic_reward_mean": economic_reward_sum / cfg.steps_per_episode,
        "projection_penalty_mean": projection_penalty_sum / cfg.steps_per_episode,
        "mapping_penalty_mean": mapping_penalty_sum / cfg.steps_per_episode,
        "feasible_action_mapping_rate": mapping_activations / cfg.steps_per_episode,
        "move_penalty_mean": move_penalty_sum / cfg.steps_per_episode,
        "safety_penalty_mean": safety_penalty_sum / cfg.steps_per_episode,
        "state_excess_squared_mean": (
            state_excess_squared_sum / cfg.steps_per_episode
        ),
        "input_excess_squared_mean": (
            input_excess_squared_sum / cfg.steps_per_episode
        ),
        "rpi_excess_squared_mean": (
            rpi_excess_squared_sum / cfg.steps_per_episode
        ),
        "violation_rate": violations / cfg.steps_per_episode,
        "rpi_violation_rate": rpi_violations / cfg.steps_per_episode,
        "disturbance_bound_exceedance_rate": (
            bound_exceedances / cfg.steps_per_episode
        ),
        "intervention_rate": interventions / cfg.steps_per_episode,
        "qp_infeasible_rate": infeasible / cfg.steps_per_episode,
        "rpi_utilization_peak": rpi_utilization_peak,
        "alpha": float(getattr(agent, "alpha", 0.0)),
        "entropy": entropy,
        "q_loss": q_loss,
        "actor_loss": actor_loss,
        "execution_mask_mean": float(np.mean([
            record["execution_mask"] for record in records
        ])),
    }
    return stats, records, global_step


def records_to_arrays(records: list[dict[str, object]]) -> dict[str, np.ndarray]:
    keys = [
        "time", "state", "control", "disturbance", "raw_action", "residual",
        "applied_residual", "execution_mask",
        "feasible_action_mapping_scale", "feasible_action_mapping_gap",
        "base", "nominal_control", "ancillary",
        "reward", "economic_cost", "economic_reward", "projection_penalty",
        "mapping_penalty",
        "move_penalty", "safety_penalty", "state_excess_squared",
        "input_excess_squared", "rpi_excess_squared",
        "violation", "rpi_violation", "projection_gap",
        "candidate", "nominal", "error", "effective_w",
    ]
    return {key: np.asarray([record[key] for record in records]) for key in keys}


def save_csv(path: Path, header: list[str], rows) -> None:
    with path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.writer(stream)
        writer.writerow(header)
        writer.writerows(rows)


def save_rollout_csv(path: Path, rollout: dict[str, np.ndarray]) -> None:
    """Write either the trained-SAC or no-RL rollout with identical columns."""
    save_csv(
        path,
        [
            "time_min", "X2", "P2", "P100", "F200",
            "F1", "X1", "T1", "T200",
            "actor_a1", "actor_a2", "residual_P100", "residual_F200",
            "applied_residual_P100", "applied_residual_F200", "execution_mask",
            "feasible_action_mapping_scale", "feasible_action_mapping_gap",
            "base_P100_norm", "base_F200_norm",
            "candidate_P100_norm", "candidate_F200_norm",
            "qp_nominal_P100_norm", "qp_nominal_F200_norm",
            "hinf_feedback_P100_norm", "hinf_feedback_F200_norm",
            "reward", "economic_cost", "economic_reward",
            "projection_penalty", "mapping_penalty", "move_penalty", "safety_penalty",
            "state_excess_squared", "input_excess_squared", "rpi_excess_squared",
            "violation", "rpi_violation", "projection_gap",
            "e_X2_norm", "e_P2_norm", "w_X2_norm", "w_P2_norm",
        ],
        (
            [
                rollout["time"][i],
                *rollout["state"][i],
                *rollout["control"][i],
                *rollout["disturbance"][i],
                *rollout["raw_action"][i],
                *rollout["residual"][i],
                *rollout["applied_residual"][i],
                rollout["execution_mask"][i],
                rollout["feasible_action_mapping_scale"][i],
                rollout["feasible_action_mapping_gap"][i],
                *rollout["base"][i],
                *rollout["candidate"][i],
                *rollout["nominal_control"][i],
                *rollout["ancillary"][i],
                rollout["reward"][i],
                rollout["economic_cost"][i],
                rollout["economic_reward"][i],
                rollout["projection_penalty"][i],
                rollout["mapping_penalty"][i],
                rollout["move_penalty"][i],
                rollout["safety_penalty"][i],
                rollout["state_excess_squared"][i],
                rollout["input_excess_squared"][i],
                rollout["rpi_excess_squared"][i],
                rollout["violation"][i],
                rollout["rpi_violation"][i],
                rollout["projection_gap"][i],
                *rollout["error"][i],
                *rollout["effective_w"][i],
            ]
            for i in range(len(rollout["time"]))
        ),
    )


def save_theta_design(path: Path, design) -> None:
    """Persist the complete online safety parameterization with a checkpoint."""
    np.savez_compressed(
        path,
        h=design.theta_h,
        p=design.theta_p,
        M=design.theta_m_matrix,
        m=design.theta_m_bound,
        K=design.k,
        W_vertices=design.w_vertices,
        W_data_hull=design.w_data_hull,
        M_angle=design.theta_m_angle,
        A=design.a,
        B=design.b,
        affine=design.affine,
        rpi_boundary=design.rpi_boundary,
        rpi_support_lower=design.rpi_support_lower,
        rpi_support_upper=design.rpi_support_upper,
        x_lower_tight=design.x_lower_tight,
        x_upper_tight=design.x_upper_tight,
        u_lower_tight=design.u_lower_tight,
        u_upper_tight=design.u_upper_tight,
        invariant_lower=design.invariant_lower,
        invariant_upper=design.invariant_upper,
        nominal_policy_gain=design.nominal_policy_gain,
        nominal_policy_offset=design.nominal_policy_offset,
    )


def evaluate_policy(
    cfg: ExperimentConfig,
    model: EvaporatorModel,
    design,
    agent,
    seeds: list[int],
) -> tuple[dict[str, float], list[dict[str, object]], list[dict[str, float]]]:
    """Evaluate deterministic control on common seeds and average all metrics."""
    samples: list[dict[str, float]] = []
    representative: list[dict[str, object]] = []
    for index, seed in enumerate(seeds):
        stat, records, _ = run_episode(
            cfg,
            model,
            SafeController(cfg, model, design),
            agent,
            None,
            np.random.default_rng(seed),
            training=False,
            global_step=0,
        )
        samples.append(stat)
        if index == 0:
            representative = records
    aggregate = {
        key: float(np.mean([sample[key] for sample in samples]))
        for key in samples[0]
    }
    return aggregate, representative, samples


def compute_safe_steady_reference(
    cfg: ExperimentConfig,
    model: EvaporatorModel,
    design,
) -> dict[str, object]:
    """Grid-search a nominal safe steady reference for evaluation only."""
    points = int(cfg.safe_reference_grid_points)
    if points < 2:
        raise ValueError("safe_reference_grid_points must be at least two")
    axes = [
        np.linspace(design.invariant_lower[i], design.invariant_upper[i], points)
        for i in range(2)
    ]
    best: dict[str, object] | None = None
    for x0 in axes[0]:
        for x1 in axes[1]:
            state_n = np.array([x0, x1], dtype=float)
            state = model.physical_state(state_n)
            control = model.steady_input(state, cfg.disturbance_nominal)
            if not np.all(np.isfinite(control)):
                continue
            derivative = model.derivative(state, control, cfg.disturbance_nominal)
            control_n = model.normalized_input(control)
            feasible = bool(
                np.max(np.abs(derivative))
                <= float(cfg.safe_reference_derivative_tolerance)
                and np.all(control_n >= design.u_lower_tight - 1e-10)
                and np.all(control_n <= design.u_upper_tight + 1e-10)
                and np.all(state_n >= design.invariant_lower - 1e-10)
                and np.all(state_n <= design.invariant_upper + 1e-10)
                and np.all(state >= cfg.state_lower - 1e-10)
                and np.all(state <= cfg.state_upper + 1e-10)
                and np.all(control >= cfg.input_lower - 1e-10)
                and np.all(control <= cfg.input_upper + 1e-10)
            )
            if not feasible:
                continue
            cost = model.economic_cost(state, control, cfg.disturbance_nominal)
            if np.isfinite(cost) and (best is None or cost < float(best["cost"])):
                best = {
                    "state": state.copy(),
                    "input": control.copy(),
                    "cost": float(cost),
                    "derivative_inf_norm": float(np.max(np.abs(derivative))),
                }
    if best is None:
        raise RuntimeError("No feasible nominal safe steady reference was found.")
    return best


def _paired_economic_metrics(
    baseline: dict[str, float],
    sac: dict[str, float],
    safe_reference_cost: float,
) -> tuple[float, float]:
    base_cost = float(baseline["economic_cost_mean"])
    sac_cost = float(sac["economic_cost_mean"])
    reduction = 100.0 * (base_cost - sac_cost) / max(abs(base_cost), 1e-12)
    denominator = base_cost - float(safe_reference_cost)
    gap = (
        -(sac_cost - float(safe_reference_cost)) / denominator
        if denominator > 1e-12 else float("nan")
    )
    return float(reduction), float(gap)


def evaluate_sac_policy_map(
    cfg: ExperimentConfig,
    model: EvaporatorModel,
    design,
    agent,
    grid_points: int = 31,
) -> dict[str, np.ndarray]:
    """Evaluate deterministic actor dependence on state over invariant S."""
    x_axis_n = np.linspace(
        design.invariant_lower[0], design.invariant_upper[0], grid_points
    )
    p_axis_n = np.linspace(
        design.invariant_lower[1], design.invariant_upper[1], grid_points
    )
    x2, p2 = np.meshgrid(
        model.physical_state(np.column_stack([
            x_axis_n, np.full_like(x_axis_n, design.z_ref[1])
        ]))[:, 0],
        model.physical_state(np.column_stack([
            np.full_like(p_axis_n, design.z_ref[0]), p_axis_n
        ]))[:, 1],
    )
    requested = np.zeros((grid_points, grid_points, ACTION_DIM), dtype=float)
    applied = np.zeros_like(requested)
    mapping_scale = np.ones((grid_points, grid_points), dtype=float)
    for row, p_value_n in enumerate(p_axis_n):
        for column, x_value_n in enumerate(x_axis_n):
            state_n = np.array([x_value_n, p_value_n], dtype=float)
            state = model.physical_state(state_n)
            controller = SafeController(cfg, model, design)
            controller.reset(state)
            obs = observation(model, controller, state, design.v_ref)
            raw_action = agent.select_action(obs, deterministic=True)
            residual = cfg.residual_action_scale * raw_action
            _, info = controller.act(state, residual)
            requested[row, column] = residual * cfg.input_scale
            applied[row, column] = (
                np.asarray(info["nominal"]) - np.asarray(info["base"])
            ) * cfg.input_scale
            mapping_scale[row, column] = float(
                info["feasible_action_mapping_scale"]
            )
    return {
        "X2": x2,
        "P2": p2,
        "requested_physical": requested,
        "applied_physical": applied,
        "mapping_scale": mapping_scale,
    }


def save_feedback_law(
    cfg: ExperimentConfig,
    design,
    output_dir: Path,
    policy_output_scale: float = 1.0,
) -> dict[str, object]:
    """Save the exact normalized and physical H-infinity feedback convention."""
    k_physical = (
        np.diag(cfg.input_scale)
        @ design.k
        @ np.diag(1.0 / cfg.state_scale)
    )
    payload = {
        "control_structure": (
            "v_theta = first affine action of the learned finite-horizon "
            "quadratic nominal value model; base = safe projection(v_theta); "
            "candidate = feasible_ray_map(base, residual_SAC); "
            "v_qp = safety verification projection(candidate); "
            "u_normalized = v_qp + K(x-z)"
        ),
        "safety_filter_type": (
            "learned finite-horizon nominal guidance plus RPI tightening and "
            "one-step invariant QP"
        ),
        "disturbance_available_to_sac": False,
        "K_parameterization": (
            "continuous real 2x2 gain with H-infinity/RPI/QP safety-gated "
            + (
                "offline geometry search and fixed SAC deployment"
                if cfg.experiment_mode == "proposed"
                else "online two-sided policy search"
            )
        ),
        "terminal_center_source": "Zanon-Gros-2020 evaporation example",
        "K_normalized": design.k.tolist(),
        "theta_h": design.theta_h.tolist(),
        "theta_p": design.theta_p.tolist(),
        "theta_M": design.theta_m_matrix.tolist(),
        "theta_m": design.theta_m_bound.tolist(),
        "K_physical_input_per_physical_state": k_physical.tolist(),
        "state_order": ["X2_percent", "P2_kPa"],
        "input_order": ["P100_kPa", "F200_kg_per_min"],
        "state_normalization_offset": cfg.linearization_state.tolist(),
        "state_normalization_scale": cfg.state_scale.tolist(),
        "input_normalization_offset": cfg.linearization_input.tolist(),
        "input_normalization_scale": cfg.input_scale.tolist(),
        "z_reference_normalized": design.z_ref.tolist(),
        "v_reference_normalized": design.v_ref.tolist(),
        "controlled_invariant_lower_normalized": design.invariant_lower.tolist(),
        "controlled_invariant_upper_normalized": design.invariant_upper.tolist(),
        "sac_residual_scale_normalized": cfg.residual_action_scale.tolist(),
        "selected_policy_output_scale": float(policy_output_scale),
        "hinf_gamma_design": design.gamma_design,
        "hinf_norm_frequency_grid": design.gamma_sampled,
    }
    with (output_dir / "feedback_control_law.json").open(
        "w", encoding="utf-8"
    ) as stream:
        json.dump(payload, stream, indent=2, ensure_ascii=False)
    text_lines = [
        "Evaporator safe-SAC feedback law",
        "",
        "Normalized coordinates:",
        "  x_n = (x - x_offset) / x_scale",
        "  u_n = (u - u_offset) / u_scale",
        "  e   = x_n - z",
        "",
        "Control sequence:",
        "  v_theta   = K_nominal(theta_h, theta_p) @ z + k_nominal(theta_h, theta_p)",
        "  base      = safe_projection(v_theta)",
        "  candidate = feasible_ray_map(base, residual_SAC, U-KZ, S)",
        "  v_qp      = Euclidean projection with v_qp in U-KZ and z_next in S",
        "  u_n       = v_qp + K @ e",
        "  u         = u_offset + u_scale * u_n",
        "",
        f"K_normalized = {np.array2string(design.k, precision=9)}",
        f"K_physical   = {np.array2string(k_physical, precision=9)}",
        f"S_lower_norm = {np.array2string(design.invariant_lower, precision=9)}",
        f"S_upper_norm = {np.array2string(design.invariant_upper, precision=9)}",
        f"selected_SAC_output_scale = {float(policy_output_scale):.6g}",
        "",
        "The four exogenous disturbances act on the plant but are not inputs "
        "to the SAC observation.",
    ]
    with (output_dir / "feedback_control_law.txt").open(
        "w", encoding="utf-8"
    ) as stream:
        stream.write("\n".join(text_lines) + "\n")
    return payload


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Continuous SAC + H-infinity/RPI/QP evaporator training"
    )
    parser.add_argument("--episodes", type=int, default=300)
    parser.add_argument("--steps", type=int, default=2000)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--experiment-mode",
        choices=("proposed", "joint_theta"),
        default="proposed",
    )
    parser.add_argument("--device", default="auto", help="auto, cpu, cuda, cuda:0, ...")
    parser.add_argument("--resume", type=Path, default=None)
    parser.add_argument(
        "--resume-theta",
        type=Path,
        default=None,
        help="matching best_theta.npz or last_theta.npz",
    )
    parser.add_argument("--output-dir", type=Path, default=None)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cfg = ExperimentConfig(
        episodes=args.episodes,
        steps_per_episode=args.steps,
        seed=args.seed,
        experiment_mode=args.experiment_mode,
    )
    if cfg.experiment_mode not in {"proposed", "joint_theta"}:
        raise ValueError("experiment_mode must be 'proposed' or 'joint_theta'")
    if args.output_dir is not None:
        cfg.output_dir = args.output_dir
    cfg.output_dir.mkdir(parents=True, exist_ok=True)
    model_dir = cfg.output_dir / "models"
    model_dir.mkdir(parents=True, exist_ok=True)

    set_seed(cfg.seed)
    rng = np.random.default_rng(cfg.seed)
    model = EvaporatorModel(cfg)
    design = build_safety_design(cfg, model, rng)
    if args.resume_theta is not None:
        with np.load(args.resume_theta) as saved_theta:
            design = build_safety_design(
                cfg,
                model,
                np.random.default_rng(cfg.seed + 16001),
                w_data_hull=saved_theta["W_data_hull"],
                theta_m_angle=float(saved_theta["M_angle"]),
                theta_h=saved_theta["h"],
                theta_p=saved_theta["p"],
                theta_k=saved_theta["K"],
            )
    initial_fixed_design = copy.deepcopy(design)
    theta_learner = OnlineThetaLearner(
        cfg,
        model,
        design,
        np.random.default_rng(cfg.seed + 17001),
    )
    if cfg.experiment_mode == "proposed":
        design, _ = theta_learner.optimize_static_safety_design(design)
    optimized_fixed_design = copy.deepcopy(design)
    controller = SafeController(cfg, model, design)
    sac_cfg = SACConfig(
        gamma=cfg.gamma_rl,
        tau=cfg.tau,
        actor_lr=cfg.actor_learning_rate,
        critic_lr=cfg.critic_learning_rate,
        alpha_lr=cfg.entropy_learning_rate,
        hidden_dim=cfg.hidden_dim,
        alpha=cfg.alpha_initial,
        alpha_min=cfg.alpha_min,
        entropy_tuning_warmup_updates=cfg.entropy_tuning_warmup_updates,
        auto_entropy_tuning=cfg.auto_entropy_tuning,
        target_entropy=cfg.target_entropy,
        actor_ema_decay=cfg.actor_ema_decay,
    )
    agent = SACAgent(OBS_DIM, ACTION_DIM, sac_cfg, device=args.device)
    agent.zero_initialize_residual_mean()
    replay = ReplayBuffer(
        OBS_DIM,
        ACTION_DIM,
        cfg.replay_capacity,
        agent.device,
    )
    if args.resume is not None:
        agent.load_checkpoint(args.resume)

    print("Continuous evaporator SAC training setup:")
    print(f"  device             : {agent.device}")
    print(f"  episodes x steps   : {cfg.episodes} x {cfg.steps_per_episode}")
    print(f"  total interactions : {cfg.episodes * cfg.steps_per_episode}")
    print(f"  obs/action dim     : {OBS_DIM}/{ACTION_DIM}")
    print(f"  hidden layers      : {cfg.hidden_dim}, {cfg.hidden_dim}")
    print(f"  replay capacity    : {cfg.replay_capacity}")
    print(f"  replay memory MiB  : {replay.allocated_bytes / 1024**2:.2f}")
    print(f"  warm-up steps      : {cfg.warmup_steps}")
    print(f"  actor learning rate: {cfg.actor_learning_rate}")
    print(f"  critic learning rate: {cfg.critic_learning_rate}")
    print(f"  entropy learning rate: {cfg.entropy_learning_rate}")
    print(f"  residual range     : {cfg.residual_action_scale.tolist()}")
    print(f"  QP square weight   : {cfg.projection_penalty_weight}")
    print(f"  entropy alpha floor: {cfg.alpha_min}")
    print(f"  training init span : {cfg.training_initial_radius_fraction:.0%} of invariant set")
    print(f"  disturbance input  : hidden from SAC, applied to plant")
    print(f"  nominal linearized : economic steady state {cfg.linearization_state.tolist()}")
    print(f"  safety anchor      : {cfg.safe_center_state.tolist()}")
    print(f"  experiment mode    : {cfg.experiment_mode}")
    print(
        "  theta path         : "
        + (
            "offline M/K geometry optimization; fixed during SAC"
            if cfg.experiment_mode == "proposed"
            else "online h, p, four-facet M, K (paper-inspired baseline)"
        )
    )
    print(f"  safe subtrajectory : {cfg.training_segment_steps} training steps")
    print(f"  theta set interval : {cfg.theta_set_update_every_episodes} episodes")
    print(f"  continuous K interval: {cfg.theta_k_update_every_episodes} episodes")
    print(f"  periodic eval seeds: {cfg.evaluation_seed_count}")
    print(f"  robustness seeds   : {cfg.holdout_seed_count}")
    print(f"  output             : {cfg.output_dir.resolve()}")

    evaluation_seeds = [
        cfg.seed + 10000 + index for index in range(cfg.evaluation_seed_count)
    ]
    no_rl_policy = ZeroResidualPolicy()
    safe_reference = compute_safe_steady_reference(cfg, model, design)
    safe_reference_cost = float(safe_reference["cost"])
    # Direct continuous policy search for K uses the same hidden-disturbance
    # seeds and the paper center for every proposal.  This avoids confounding a
    # gain change with a different random initial state.  Unsafe rollouts are
    # rejected in addition to the offline H-infinity/RPI feasibility gate.
    k_evaluation_cfg = replace(
        cfg,
        steps_per_episode=min(
            int(cfg.theta_k_evaluation_steps), cfg.steps_per_episode
        ),
        evaluation_initial_radius_fraction=0.0,
    )
    k_evaluation_seeds = [
        cfg.seed + 40000 + index
        for index in range(cfg.theta_k_evaluation_seed_count)
    ]

    def evaluate_continuous_k(candidate_design) -> float:
        candidate_stat, _, _ = evaluate_policy(
            k_evaluation_cfg,
            model,
            candidate_design,
            agent,
            k_evaluation_seeds,
        )
        safe = (
            candidate_stat["violation_rate"] == 0.0
            and candidate_stat["rpi_violation_rate"] == 0.0
            and candidate_stat["qp_infeasible_rate"] == 0.0
        )
        return (
            float(candidate_stat["return_per_step"])
            if safe else -float("inf")
        )

    initial_stat, _, _ = evaluate_policy(
        cfg, model, design, agent, evaluation_seeds
    )
    initial_baseline_stat, _, _ = evaluate_policy(
        cfg, model, design, no_rl_policy, evaluation_seeds
    )
    initial_reduction, initial_gap = _paired_economic_metrics(
        initial_baseline_stat, initial_stat, safe_reference_cost
    )
    initial_theta_metrics = theta_learner.metrics(design)
    logs: list[dict[str, float]] = [{
        "episode": 0,
        **initial_stat,
        **initial_theta_metrics,
        "evaluation_return": initial_stat["return"],
        "evaluation_return_per_step": initial_stat["return_per_step"],
        "evaluation_economic_cost_mean": initial_stat["economic_cost_mean"],
        "evaluation_theta_only_economic_cost_mean": initial_baseline_stat["economic_cost_mean"],
        "evaluation_safe_sac_economic_cost_mean": initial_stat["economic_cost_mean"],
        "evaluation_sac_incremental_cost_reduction_percent": initial_reduction,
        "evaluation_normalized_safe_performance_gap": initial_gap,
        "safe_reference_cost": safe_reference_cost,
    }]
    global_step = 0
    best_eval_return_per_step = float(initial_stat["return_per_step"])
    best_eval_episode = 0
    best_design = copy.deepcopy(design)
    policy_candidates: list[dict[str, object]] = [{
        "episode": 0,
        "online_return_per_step": float(initial_stat["return_per_step"]),
        "actor_state": copy.deepcopy(agent.actor.state_dict()),
        "zero_fallback": True,
    }]
    agent.save_actor(model_dir / "best_actor.pth")
    agent.save_checkpoint(model_dir / "best_checkpoint.pth")
    save_theta_design(model_dir / "initial_theta.npz", initial_fixed_design)
    save_theta_design(model_dir / "optimized_theta.npz", optimized_fixed_design)
    save_theta_design(model_dir / "best_theta.npz", best_design)
    print(
        "episode=000/"
        f"{cfg.episodes} eval_per_step={initial_stat['return_per_step']:.6f} "
        f"economic_cost={initial_stat['economic_cost_mean']:.3f}",
        flush=True,
    )
    start = time.time()
    for episode in range(1, cfg.episodes + 1):
        stat, _, global_step = run_episode(
            cfg,
            model,
            controller,
            agent,
            replay,
            rng,
            training=True,
            global_step=global_step,
            theta_learner=theta_learner,
        )
        agent.update_actor_ema()
        if cfg.experiment_mode == "joint_theta":
            design, theta_metrics = theta_learner.update_after_episode(
                episode, design, design_evaluator=evaluate_continuous_k
            )
            controller = SafeController(cfg, model, design)
        else:
            # Transitions are retained for diagnostics, but the optimized
            # H-infinity/RPI/QP design is immutable throughout SAC training.
            theta_metrics = theta_learner.metrics(design)

        eval_return = float("nan")
        eval_return_per_step = float("nan")
        eval_economic_cost_mean = float("nan")
        eval_theta_only_cost = float("nan")
        eval_sac_cost = float("nan")
        eval_cost_reduction = float("nan")
        eval_safe_gap = float("nan")
        if (
            episode == 1
            or episode % cfg.evaluation_every == 0
            or episode == cfg.episodes
        ):
            eval_stat, _, _ = evaluate_policy(
                cfg, model, design, agent, evaluation_seeds
            )
            eval_return = float(eval_stat["return"])
            eval_return_per_step = float(eval_stat["return_per_step"])
            eval_economic_cost_mean = float(eval_stat["economic_cost_mean"])
            eval_baseline_stat, _, _ = evaluate_policy(
                cfg, model, design, no_rl_policy, evaluation_seeds
            )
            eval_theta_only_cost = float(eval_baseline_stat["economic_cost_mean"])
            eval_sac_cost = eval_economic_cost_mean
            eval_cost_reduction, eval_safe_gap = _paired_economic_metrics(
                eval_baseline_stat, eval_stat, safe_reference_cost
            )
            eval_safe = (
                eval_stat["violation_rate"] == 0.0
                and eval_stat["rpi_violation_rate"] == 0.0
                and eval_stat["qp_infeasible_rate"] == 0.0
            )
            policy_candidates.append({
                "episode": int(episode),
                "online_return_per_step": eval_return_per_step,
                "actor_state": copy.deepcopy(agent.actor.state_dict()),
                "zero_fallback": False,
            })
            if eval_safe and eval_return_per_step > best_eval_return_per_step:
                best_eval_return_per_step = eval_return_per_step
                best_eval_episode = episode
                best_design = copy.deepcopy(design)
                agent.save_actor(model_dir / "best_actor.pth")
                agent.save_checkpoint(model_dir / "best_checkpoint.pth")
                save_theta_design(model_dir / "best_theta.npz", best_design)

        if episode % cfg.save_every == 0 or episode == cfg.episodes:
            agent.save_actor(model_dir / "last_actor.pth")
            agent.save_checkpoint(model_dir / "last_checkpoint.pth")
            save_theta_design(model_dir / "last_theta.npz", design)

        logs.append({
            "episode": episode,
            **stat,
            **theta_metrics,
            "evaluation_return": eval_return,
            "evaluation_return_per_step": eval_return_per_step,
            "evaluation_economic_cost_mean": eval_economic_cost_mean,
            "evaluation_theta_only_economic_cost_mean": eval_theta_only_cost,
            "evaluation_safe_sac_economic_cost_mean": eval_sac_cost,
            "evaluation_sac_incremental_cost_reduction_percent": eval_cost_reduction,
            "evaluation_normalized_safe_performance_gap": eval_safe_gap,
            "safe_reference_cost": safe_reference_cost,
        })
        if episode == 1 or episode % 10 == 0:
            eval_text = (
                f" eval_cost={eval_economic_cost_mean:.3f}"
                if np.isfinite(eval_economic_cost_mean) else ""
            )
            print(
                f"episode={episode:03d}/{cfg.episodes} "
                f"return={stat['return']:.3f} "
                f"per_step={stat['return_per_step']:.4f} "
                f"violation={stat['violation_rate']:.4f} "
                f"rpi={stat['rpi_violation_rate']:.4f} "
                f"intervention={stat['intervention_rate']:.3f} "
                f"alpha={stat['alpha']:.4f}"
                f" M_updates={int(theta_metrics['theta_set_update_accepts'])}"
                f" K_updates={int(theta_metrics['theta_K_update_accepts'])}"
                f"{eval_text}",
                flush=True,
            )

    # Preserve and assess the raw final actor before final-data certification.
    last_stat, _, _ = evaluate_policy(
        cfg, model, design, agent, evaluation_seeds
    )
    holdout_seeds = [
        cfg.seed + 20000 + index for index in range(cfg.holdout_seed_count)
    ]
    holdout_last_stat, _, _ = evaluate_policy(
        cfg, model, design, agent, holdout_seeds
    )
    training_gradient_updates = int(agent.total_updates)

    # The joint-theta ablation rebuilds against its final hull.  The proposed
    # mode deliberately keeps the offline design fixed and only audits newly
    # observed residuals against it.
    final_data_hull = np.asarray(theta_learner.data_hull, dtype=float).copy()
    if cfg.experiment_mode == "joint_theta":
        design = build_safety_design(
            cfg,
            model,
            np.random.default_rng(cfg.seed + 51001),
            w_data_hull=final_data_hull,
            theta_m_angle=design.theta_m_angle,
            theta_h=design.theta_h,
            theta_p=design.theta_p,
            theta_k=design.k,
        )
    uncovered_final_vertices = sum(
        not point_in_convex_polygon(point, design.w_vertices, tol=1e-8)
        for point in final_data_hull
    )
    if uncovered_final_vertices and cfg.experiment_mode == "joint_theta":
        raise RuntimeError(
            "Final safety design does not contain every retained disturbance "
            f"vertex ({uncovered_final_vertices} uncovered)."
        )
    if uncovered_final_vertices and cfg.experiment_mode == "proposed":
        print(
            "WARNING: fixed proposed safety design did not contain all observed "
            f"effective-disturbance hull vertices ({uncovered_final_vertices}); "
            "final certification will be marked failed.",
            flush=True,
        )

    # Select the SAC policy only after all candidates have been placed behind
    # the same final certified theta.  The paired zero-residual result is a
    # hard lower-performance gate; scale=0 remains an honest safe fallback.
    theta_only_stat, theta_only_records, _ = evaluate_policy(
        cfg, model, design, no_rl_policy, evaluation_seeds
    )
    ranked_candidates = sorted(
        policy_candidates,
        key=lambda item: float(item["online_return_per_step"]),
        reverse=True,
    )
    if int(cfg.sac_final_candidate_count) > 0:
        ranked_candidates = ranked_candidates[:int(cfg.sac_final_candidate_count)]
    if not any(bool(item.get("zero_fallback", False)) for item in ranked_candidates):
        ranked_candidates.append(policy_candidates[0])
    if not any(int(item["episode"]) == cfg.episodes for item in ranked_candidates):
        ranked_candidates.append(policy_candidates[-1])

    selected_candidate: dict[str, object] | None = None
    candidate_audit: list[dict[str, float]] = []
    for candidate in ranked_candidates:
        agent.actor.load_state_dict(candidate["actor_state"])
        agent.actor_ema.load_state_dict(candidate["actor_state"])
        candidate_scales = (
            (0.0,)
            if bool(candidate.get("zero_fallback", False))
            else tuple(cfg.sac_selection_scales)
        )
        for policy_scale in candidate_scales:
            agent.set_policy_output_scale(policy_scale)
            candidate_stat, _, _ = evaluate_policy(
                cfg, model, design, agent, evaluation_seeds
            )
            incremental_return = float(
                candidate_stat["return_per_step"]
                - theta_only_stat["return_per_step"]
            )
            safe = bool(
                candidate_stat["violation_rate"] == 0.0
                and candidate_stat["rpi_violation_rate"] == 0.0
                and candidate_stat["qp_infeasible_rate"] == 0.0
            )
            positive_increment = bool(
                policy_scale > 0.0
                and safe
                and candidate_stat["economic_cost_mean"]
                < theta_only_stat["economic_cost_mean"] - 1e-12
                and incremental_return
                >= float(cfg.sac_min_incremental_return_per_step) - 1e-12
            )
            zero_fallback = bool(
                policy_scale == 0.0 and candidate.get("zero_fallback", False)
            )
            eligible = bool(zero_fallback or positive_increment)
            cost_reduction_percent = float(
                100.0
                * (theta_only_stat["economic_cost_mean"] - candidate_stat["economic_cost_mean"])
                / max(abs(theta_only_stat["economic_cost_mean"]), 1e-12)
            )
            # Always retain an honest scale=0 diagnostic fallback.  It is not
            # mislabeled as certified when the fixed design itself is violated.
            eligible = bool(zero_fallback or (safe and eligible))
            audit_row = {
                "episode": float(candidate["episode"]),
                "policy_scale": float(policy_scale),
                "return_per_step": float(candidate_stat["return_per_step"]),
                "economic_cost_mean": float(candidate_stat["economic_cost_mean"]),
                "incremental_return_per_step": incremental_return,
                "economic_cost_reduction_percent": cost_reduction_percent,
                "violation_rate": float(candidate_stat["violation_rate"]),
                "rpi_violation_rate": float(candidate_stat["rpi_violation_rate"]),
                "qp_infeasible_rate": float(candidate_stat["qp_infeasible_rate"]),
                "disturbance_bound_exceedance_rate": float(
                    candidate_stat["disturbance_bound_exceedance_rate"]
                ),
                "intervention_rate": float(candidate_stat["intervention_rate"]),
                "mapping_rate": float(candidate_stat["feasible_action_mapping_rate"]),
                "safe": float(safe),
                "positive_increment": float(positive_increment),
                "eligible": float(eligible),
            }
            candidate_audit.append(audit_row)
            if eligible and (
                selected_candidate is None
                or (
                    audit_row["economic_cost_mean"],
                    -audit_row["return_per_step"],
                    audit_row["intervention_rate"],
                )
                < (
                    float(selected_candidate["economic_cost_mean"]),
                    -float(selected_candidate["return_per_step"]),
                    float(selected_candidate["intervention_rate"]),
                )
            ):
                selected_candidate = {
                    **audit_row,
                    "actor_state": copy.deepcopy(candidate["actor_state"]),
                }

    if selected_candidate is None:
        raise RuntimeError(
            "No final-data-certified policy passed the paired theta-only gate."
        )
    agent.actor.load_state_dict(selected_candidate["actor_state"])
    agent.actor_ema.load_state_dict(selected_candidate["actor_state"])
    agent.set_policy_output_scale(float(selected_candidate["policy_scale"]))
    best_eval_episode = int(selected_candidate["episode"])
    best_eval_return_per_step = float(selected_candidate["return_per_step"])
    best_design = copy.deepcopy(design)
    agent.save_actor(model_dir / "best_actor.pth")
    agent.save_checkpoint(model_dir / "best_checkpoint.pth")
    save_theta_design(model_dir / "best_theta.npz", design)
    save_csv(
        cfg.output_dir / "final_checkpoint_audit.csv",
        list(candidate_audit[0].keys()),
        ([row[key] for key in candidate_audit[0]] for row in candidate_audit),
    )

    final_stat, final_records, _ = evaluate_policy(
        cfg, model, design, agent, evaluation_seeds
    )
    holdout_best_stat, _, _ = evaluate_policy(
        cfg, model, design, agent, holdout_seeds
    )

    # Two controlled ablations on paired seeds:
    # (1) learned theta with the SAC residual removed; and
    # (2) fixed initial theta with no SAC, which is the true no-learning case.
    holdout_theta_only_stat, _, _ = evaluate_policy(
        cfg, model, design, no_rl_policy, holdout_seeds
    )
    no_rl_stat, no_rl_records, _ = evaluate_policy(
        cfg, model, initial_fixed_design, no_rl_policy, evaluation_seeds
    )
    holdout_no_rl_stat, _, _ = evaluate_policy(
        cfg, model, initial_fixed_design, no_rl_policy, holdout_seeds
    )
    nonzero_audit = [
        row for row in candidate_audit if float(row["policy_scale"]) > 0.0
    ]
    best_nonzero = min(
        nonzero_audit,
        key=lambda row: (
            float(row["economic_cost_mean"]),
            float(row["violation_rate"]),
            float(row["intervention_rate"]),
        ),
        default=None,
    )

    rollout = records_to_arrays(final_records)
    theta_only_rollout = records_to_arrays(theta_only_records)
    no_rl_rollout = records_to_arrays(no_rl_records)
    log_arrays = {
        key: np.asarray([row[key] for row in logs], dtype=float)
        for key in logs[0]
    }
    save_csv(
        cfg.output_dir / "training_log.csv",
        list(logs[0].keys()),
        ([row[key] for key in logs[0]] for row in logs),
    )
    eval_mask = np.isfinite(log_arrays["evaluation_return_per_step"])
    eval_episodes = log_arrays["episode"][eval_mask]
    eval_values = log_arrays["evaluation_return_per_step"][eval_mask]
    eval_best_so_far = np.maximum.accumulate(eval_values)
    eval_best = float(np.max(eval_values))
    eval_scale = max(eval_best - float(eval_values[0]), 1e-12)
    empirical_regret = (eval_best_so_far - eval_best) / eval_scale
    save_csv(
        cfg.output_dir / "empirical_regret.csv",
        [
            "episode",
            "evaluation_return_per_step",
            "best_so_far_return_per_step",
            "normalized_empirical_regret",
        ],
        zip(eval_episodes, eval_values, eval_best_so_far, empirical_regret),
    )
    save_rollout_csv(cfg.output_dir / "evaluation_rollout.csv", rollout)
    save_rollout_csv(cfg.output_dir / "theta_only_rollout.csv", theta_only_rollout)
    save_rollout_csv(cfg.output_dir / "no_rl_rollout.csv", no_rl_rollout)
    np.savez_compressed(
        cfg.output_dir / "safety_design.npz",
        A=design.a,
        B=design.b,
        affine=design.affine,
        K=design.k,
        h=design.theta_h,
        p=design.theta_p,
        M=design.theta_m_matrix,
        m=design.theta_m_bound,
        W=design.w_bound,
        disturbance_vertices=design.w_vertices,
        disturbance_data_hull=design.w_data_hull,
        rpi_boundary=design.rpi_boundary,
        rpi_support=design.rpi_support,
        rpi_support_lower=design.rpi_support_lower,
        rpi_support_upper=design.rpi_support_upper,
        box_reference_rpi_width_physical=design.box_reference_rpi_width_physical,
        box_reference_rpi_area_physical=design.box_reference_rpi_area_physical,
        invariant_lower=design.invariant_lower,
        invariant_upper=design.invariant_upper,
        invariant_scale=design.invariant_scale,
        gain_state_weight_scale=design.gain_state_weight_scale,
        gain_input_weight_scale=design.gain_input_weight_scale,
    )

    boundary = design.rpi_boundary
    rpi_physical = cfg.safe_center_state + boundary * cfg.state_scale
    rpi_area = 0.5 * abs(float(np.sum(
        rpi_physical[:, 0] * np.roll(rpi_physical[:, 1], -1)
        - rpi_physical[:, 1] * np.roll(rpi_physical[:, 0], -1)
    )))
    initial_rpi_physical = (
        cfg.safe_center_state
        + initial_fixed_design.rpi_boundary * cfg.state_scale
    )
    initial_rpi_area = 0.5 * abs(float(np.sum(
        initial_rpi_physical[:, 0] * np.roll(initial_rpi_physical[:, 1], -1)
        - initial_rpi_physical[:, 1] * np.roll(initial_rpi_physical[:, 0], -1)
    )))
    x_minus_z_width = (
        design.x_upper_tight - design.x_lower_tight
    ) * cfg.state_scale
    initial_x_minus_z_width = (
        initial_fixed_design.x_upper_tight
        - initial_fixed_design.x_lower_tight
    ) * cfg.state_scale
    invariant_width = (
        design.invariant_upper - design.invariant_lower
    ) * cfg.state_scale
    initial_invariant_width = (
        initial_fixed_design.invariant_upper - initial_fixed_design.invariant_lower
    ) * cfg.state_scale
    peak_w_positive = np.max(rollout["effective_w"], axis=0)
    peak_w_negative = -np.min(rollout["effective_w"], axis=0)
    training_mask = log_arrays["episode"] >= 1.0
    training_returns = log_arrays["return"][training_mask]
    nominal_economic_reference_cost = model.economic_cost(
        cfg.linearization_state,
        cfg.linearization_input,
        cfg.disturbance_nominal,
    )
    safe_center_input = model.physical_input(design.v_ref)
    safe_center_cost = model.economic_cost(
        cfg.safe_center_state,
        safe_center_input,
        cfg.disturbance_nominal,
    )
    state_constraint_area = float(np.prod(cfg.state_upper - cfg.state_lower))
    initial_x_minus_z_area = float(np.prod(initial_x_minus_z_width))
    optimized_x_minus_z_area = float(np.prod(x_minus_z_width))
    initial_invariant_area = float(np.prod(initial_invariant_width))
    optimized_invariant_area = float(np.prod(invariant_width))
    final_cost_reduction, final_safe_gap = _paired_economic_metrics(
        theta_only_stat, final_stat, safe_reference_cost
    )
    holdout_cost_reduction, _ = _paired_economic_metrics(
        holdout_theta_only_stat, holdout_best_stat, safe_reference_cost
    )
    feedback_law = save_feedback_law(
        cfg, design, cfg.output_dir, agent.policy_output_scale
    )
    final_theta_metrics = theta_learner.metrics(design)
    policy_map = evaluate_sac_policy_map(cfg, model, design, agent)
    requested_map = policy_map["requested_physical"]
    applied_map = policy_map["applied_physical"]
    policy_map_metrics = {
        "requested_residual_peak_to_peak_physical": np.ptp(
            requested_map, axis=(0, 1)
        ).tolist(),
        "applied_residual_peak_to_peak_physical": np.ptp(
            applied_map, axis=(0, 1)
        ).tolist(),
        "requested_residual_state_grid_std_physical": np.std(
            requested_map, axis=(0, 1)
        ).tolist(),
        "applied_residual_state_grid_std_physical": np.std(
            applied_map, axis=(0, 1)
        ).tolist(),
        "safe_mapping_active_grid_fraction": float(np.mean(
            policy_map["mapping_scale"] < 1.0 - 1e-10
        )),
        "interpretation": (
            "near-zero requested peak-to-peak means a constant residual bias; "
            "larger values demonstrate state-dependent actor feedback"
        ),
    }
    requested_state_dependence_norm = float(np.linalg.norm(np.ptp(
        requested_map, axis=(0, 1)
    )))
    applied_state_dependence_norm = float(np.linalg.norm(np.ptp(
        applied_map, axis=(0, 1)
    )))
    selected_positive_increment = bool(
        agent.policy_output_scale > 0.0
        and final_stat["economic_cost_mean"]
        < theta_only_stat["economic_cost_mean"] - 1e-12
        and holdout_best_stat["economic_cost_mean"]
        < holdout_theta_only_stat["economic_cost_mean"] - 1e-12
        and final_stat["violation_rate"] == 0.0
        and holdout_best_stat["violation_rate"] == 0.0
        and final_stat["rpi_violation_rate"] == 0.0
        and holdout_best_stat["rpi_violation_rate"] == 0.0
        and final_stat["qp_infeasible_rate"] == 0.0
        and holdout_best_stat["qp_infeasible_rate"] == 0.0
        and final_stat["disturbance_bound_exceedance_rate"] == 0.0
        and holdout_best_stat["disturbance_bound_exceedance_rate"] == 0.0
        and uncovered_final_vertices == 0
        and applied_state_dependence_norm > 0.0
    )
    save_csv(
        cfg.output_dir / "sac_residual_policy_map.csv",
        [
            "X2", "P2", "requested_delta_P100", "requested_delta_F200",
            "applied_delta_P100", "applied_delta_F200", "mapping_scale",
        ],
        (
            [
                policy_map["X2"][row, column],
                policy_map["P2"][row, column],
                *requested_map[row, column],
                *applied_map[row, column],
                policy_map["mapping_scale"][row, column],
            ]
            for row in range(policy_map["X2"].shape[0])
            for column in range(policy_map["X2"].shape[1])
        ),
    )
    plot_learning(log_arrays, cfg.output_dir)
    plot_theta_learning(log_arrays, cfg.output_dir)
    plot_empirical_regret(log_arrays, cfg.output_dir)
    plot_sets(cfg, model, design, boundary, rollout, cfg.output_dir)
    plot_paper_aligned_set_comparison(
        cfg,
        model,
        initial_fixed_design,
        design,
        cfg.output_dir,
    )
    plot_rollout(cfg, rollout, cfg.output_dir)
    plot_disturbances(cfg, rollout, cfg.output_dir)
    plot_disturbance_response(cfg, design, rollout, cfg.output_dir)
    plot_economic_performance(rollout, safe_center_cost, cfg.output_dir)
    plot_feedback_components(rollout, cfg.output_dir)
    plot_sac_policy_map(policy_map, cfg.output_dir)
    plot_rl_comparison(
        cfg, rollout, theta_only_rollout, no_rl_rollout, cfg.output_dir
    )

    economic_cost = rollout["economic_cost"]
    economic_performance = {
        "stage_cost_mean": float(np.mean(economic_cost)),
        "stage_cost_std": float(np.std(economic_cost)),
        "stage_cost_min": float(np.min(economic_cost)),
        "stage_cost_max": float(np.max(economic_cost)),
        "stage_cost_total": float(np.sum(economic_cost)),
        "last_10_percent_stage_cost_mean": float(np.mean(
            economic_cost[max(0, int(0.9 * len(economic_cost))):]
        )),
        "safe_center_nominal_stage_cost": safe_center_cost,
        "nominal_economic_reference_cost": nominal_economic_reference_cost,
        "stage_cost_gap_to_nominal_reference_percent": float(
            100.0
            * (np.mean(economic_cost) - nominal_economic_reference_cost)
            / max(abs(nominal_economic_reference_cost), 1e-12)
        ),
        "state_mean": np.mean(rollout["state"], axis=0).tolist(),
        "state_std": np.std(rollout["state"], axis=0).tolist(),
        "control_mean": np.mean(rollout["control"], axis=0).tolist(),
        "control_std": np.std(rollout["control"], axis=0).tolist(),
    }
    rl_vs_no_rl = {
        "comparison_design": (
            "paired seeds and identical hidden disturbances; safe_SAC uses "
            "the same optimized fixed safety design as theta_only; only the "
            "SAC residual differs. no_RL uses the initial unoptimized design"
        ),
        "safe_sac": final_stat,
        "theta_only_no_sac": theta_only_stat,
        "no_rl_fixed_theta_hinf_rpi_qp": no_rl_stat,
        "safe_sac_holdout": holdout_best_stat,
        "theta_only_no_sac_holdout": holdout_theta_only_stat,
        "no_rl_holdout": holdout_no_rl_stat,
        "economic_cost_reduction_percent": float(
            100.0
            * (no_rl_stat["economic_cost_mean"] - final_stat["economic_cost_mean"])
            / max(abs(no_rl_stat["economic_cost_mean"]), 1e-12)
        ),
        "theta_only_cost_reduction_vs_fixed_theta_percent": float(
            100.0
            * (no_rl_stat["economic_cost_mean"] - theta_only_stat["economic_cost_mean"])
            / max(abs(no_rl_stat["economic_cost_mean"]), 1e-12)
        ),
        "sac_incremental_cost_reduction_vs_theta_only_percent": float(
            final_cost_reduction
        ),
        "return_improvement": float(final_stat["return"] - no_rl_stat["return"]),
        "intervention_rate_change": float(
            final_stat["intervention_rate"] - no_rl_stat["intervention_rate"]
        ),
    }
    with (cfg.output_dir / "rl_vs_no_rl_metrics.json").open(
        "w", encoding="utf-8"
    ) as stream:
        json.dump(rl_vs_no_rl, stream, indent=2, ensure_ascii=False)
    metrics = {
        "algorithm": (
            "static_hinf_rpi_geometry_plus_fixed_qp_residual_sac"
            if cfg.experiment_mode == "proposed"
            else "joint_theta_residual_sac_ablation"
        ),
        "experiment_mode": cfg.experiment_mode,
        "experiment_scope": (
            "offline_static_hinf_rpi_geometry_then_fixed_safe_residual_sac"
            if cfg.experiment_mode == "proposed"
            else "paper_inspired_online_h_p_M_K_ablation"
        ),
        "selected_policy": "fixed_design_paired_checkpoint_scale_audit",
        "best_evaluation_episode": int(best_eval_episode),
        "best_episode": int(best_eval_episode),
        "selected_policy_output_scale": float(agent.policy_output_scale),
        "selected_policy_scale": float(agent.policy_output_scale),
        "initial_rpi_area": float(initial_rpi_area),
        "optimized_rpi_area": float(rpi_area),
        "rpi_area_reduction_percent": float(
            100.0 * (initial_rpi_area - rpi_area) / max(initial_rpi_area, 1e-12)
        ),
        "initial_x_minus_z_area": initial_x_minus_z_area,
        "optimized_x_minus_z_area": optimized_x_minus_z_area,
        "x_minus_z_area_increase_percent": float(
            100.0 * (optimized_x_minus_z_area - initial_x_minus_z_area)
            / max(initial_x_minus_z_area, 1e-12)
        ),
        "initial_invariant_area": initial_invariant_area,
        "optimized_invariant_area": optimized_invariant_area,
        "theta_only_economic_cost_mean": float(theta_only_stat["economic_cost_mean"]),
        "safe_sac_economic_cost_mean": float(final_stat["economic_cost_mean"]),
        "holdout_theta_only_economic_cost_mean": float(
            holdout_theta_only_stat["economic_cost_mean"]
        ),
        "holdout_safe_sac_economic_cost_mean": float(
            holdout_best_stat["economic_cost_mean"]
        ),
        "sac_incremental_cost_reduction_percent": final_cost_reduction,
        "holdout_sac_incremental_cost_reduction_percent": holdout_cost_reduction,
        "safe_reference_cost": safe_reference_cost,
        "normalized_safe_performance_gap": final_safe_gap,
        "nominal_safe_steady_reference": {
            "state": np.asarray(safe_reference["state"]).tolist(),
            "input": np.asarray(safe_reference["input"]).tolist(),
            "cost": safe_reference_cost,
            "derivative_inf_norm": float(safe_reference["derivative_inf_norm"]),
            "interpretation": "evaluation-only nominal safe steady reference, not a global optimal policy",
        },
        "constraint_violation_rate": float(final_stat["violation_rate"]),
        "holdout_constraint_violation_rate": float(holdout_best_stat["violation_rate"]),
        "rpi_violation_rate": float(final_stat["rpi_violation_rate"]),
        "qp_infeasible_rate": float(final_stat["qp_infeasible_rate"]),
        "qp_intervention_rate": float(final_stat["intervention_rate"]),
        "safe_action_mapping_rate": float(final_stat["feasible_action_mapping_rate"]),
        "requested_residual_state_dependence_norm": requested_state_dependence_norm,
        "applied_residual_state_dependence_norm": applied_state_dependence_norm,
        "disturbance_bound_exceedance_rate": float(
            final_stat["disturbance_bound_exceedance_rate"]
        ),
        "sac_positive_increment_learned": selected_positive_increment,
        "best_nonzero_policy_episode": (
            float(best_nonzero["episode"]) if best_nonzero is not None else float("nan")
        ),
        "best_nonzero_policy_scale": (
            float(best_nonzero["policy_scale"]) if best_nonzero is not None else float("nan")
        ),
        "best_nonzero_incremental_return": (
            float(best_nonzero["incremental_return_per_step"])
            if best_nonzero is not None else float("nan")
        ),
        "best_nonzero_cost_reduction_percent": (
            float(best_nonzero["economic_cost_reduction_percent"])
            if best_nonzero is not None else float("nan")
        ),
        "best_nonzero_violation_rate": (
            float(best_nonzero["violation_rate"]) if best_nonzero is not None else float("nan")
        ),
        "best_nonzero_intervention_rate": (
            float(best_nonzero["intervention_rate"]) if best_nonzero is not None else float("nan")
        ),
        "best_nonzero_mapping_rate": (
            float(best_nonzero["mapping_rate"]) if best_nonzero is not None else float("nan")
        ),
        "final_checkpoint_certification": {
            "checked_against_final_retained_disturbance_hull": True,
            "safety_design_rebuilt_from_final_hull": bool(
                cfg.experiment_mode == "joint_theta"
            ),
            "final_data_hull_vertex_count": int(len(final_data_hull)),
            "uncovered_final_hull_vertices": int(uncovered_final_vertices),
            "candidate_count_before_prescreen": int(len(policy_candidates)),
            "candidate_count_after_prescreen": int(len(ranked_candidates)),
            "policy_scales_tested": list(cfg.sac_selection_scales),
            "paired_theta_only_return_per_step": float(
                theta_only_stat["return_per_step"]
            ),
            "paired_theta_only_economic_cost_mean": float(
                theta_only_stat["economic_cost_mean"]
            ),
            "selected_incremental_return_per_step": float(
                final_stat["return_per_step"] - theta_only_stat["return_per_step"]
            ),
            "selected_incremental_economic_cost_reduction": float(
                theta_only_stat["economic_cost_mean"]
                - final_stat["economic_cost_mean"]
            ),
            "sac_positive_increment_learned": bool(
                selected_positive_increment
            ),
            "fixed_design_disturbance_bound_certified": bool(
                uncovered_final_vertices == 0
                and final_stat["disturbance_bound_exceedance_rate"] == 0.0
                and holdout_best_stat["disturbance_bound_exceedance_rate"] == 0.0
            ),
            "audit_file": "final_checkpoint_audit.csv",
        },
        "device": str(agent.device),
        "observation_includes_current_disturbance": False,
        "disturbance_is_applied_to_plant": True,
        "disturbance_model": "independent_bounded_uniform_hidden_input",
        "observation_dimension": OBS_DIM,
        "episodes": cfg.episodes,
        "steps_per_episode": cfg.steps_per_episode,
        "total_interactions": cfg.episodes * cfg.steps_per_episode,
        "gradient_updates": training_gradient_updates,
        "training_segment_steps": int(cfg.training_segment_steps),
        "training_subtrajectories_per_episode": int(
            np.ceil(cfg.steps_per_episode / max(cfg.training_segment_steps, 1))
        ),
        "theta_learning": {
            **final_theta_metrics,
            "h": design.theta_h.tolist(),
            "p": design.theta_p.tolist(),
            "M": design.theta_m_matrix.tolist(),
            "m": design.theta_m_bound.tolist(),
            "K": design.k.tolist(),
            "W_data_hull_vertex_count": int(len(design.w_data_hull)),
            "W_theta_vertex_count": int(len(design.w_vertices)),
            "cost_learning_rate": cfg.theta_cost_learning_rate,
            "cost_normalization_scale": cfg.theta_cost_scale,
            "set_update_every_episodes": cfg.theta_set_update_every_episodes,
            "continuous_K_update_every_episodes": cfg.theta_k_update_every_episodes,
            "frozen_during_sac": bool(cfg.experiment_mode == "proposed"),
            "continuous_K_evaluation_steps": cfg.theta_k_evaluation_steps,
            "continuous_K_parameterization": (
                "direct unconstrained real 2x2 entries with two-sided pattern "
                "search; acceptance constrained by the complete safety gate"
            ),
            "safe_acceptance_gate": (
                "all retained residuals in W_theta; stable A+BK; nonempty "
                "tightened input/state sets and controlled-invariant set"
            ),
        },
        "paper_2020_comparison": {
            "name": "paper_inspired_theta_baseline",
            "exact_2020_reproduction": False,
            "scope": (
                "paper-aligned center, linear steady input, disturbance ranges, "
                "constraints, economic cost, and theta=(h,p,M,K); SAC replaces "
                "the paper's Q-learning and the one-step invariant QP replaces "
                "its full robust MPC horizon"
            ),
            "paper_terminal_center": [29.0, 53.57],
            "paper_terminal_input_reported": [223.76, 221.61],
            "implemented_linear_terminal_input": safe_center_input.tolist(),
            "paper_discount_factor": 0.99,
            "implemented_discount_factor": cfg.gamma_rl,
            "implemented_training_interactions": cfg.episodes * cfg.steps_per_episode,
            "comparison_training_point": "completed_training_run",
            "paper_parameters_learned": ["h", "p", "M", "K"],
            "implemented_parameters_learned": (
                ["SAC_actor_critic"]
                if cfg.experiment_mode == "proposed"
                else ["h", "p", "M", "K"]
            ),
            "K_search_space": "continuous_real_2_by_2_with_safety_gated_pattern_search",
            "initial_K": initial_fixed_design.k.tolist(),
            "final_K": design.k.tolist(),
            "K_change_frobenius_norm": float(np.linalg.norm(
                design.k - initial_fixed_design.k
            )),
            "initial_rpi_area_percent_kpa": initial_rpi_area,
            "final_rpi_area_percent_kpa": rpi_area,
            "rpi_area_change_percent": float(
                100.0 * (rpi_area - initial_rpi_area)
                / max(initial_rpi_area, 1e-12)
            ),
            "initial_x_minus_z_width_physical": initial_x_minus_z_width.tolist(),
            "final_x_minus_z_width_physical": x_minus_z_width.tolist(),
            "initial_x_minus_z_area_percent_kpa": float(np.prod(
                initial_x_minus_z_width
            )),
            "final_x_minus_z_area_percent_kpa": float(np.prod(x_minus_z_width)),
            "numeric_paper_set_areas_available": False,
            "comparison_limit": (
                "the paper plots initial/final sets but does not tabulate their "
                "areas; no numeric paper area is fabricated"
            ),
        },
        "training_seconds": time.time() - start,
        "evaluation": final_stat,
        "initial_untrained_evaluation": initial_stat,
        "raw_last_actor_evaluation": last_stat,
        "robustness_evaluation_best_policy": holdout_best_stat,
        "robustness_evaluation_raw_last_policy": holdout_last_stat,
        "rl_vs_no_rl": rl_vs_no_rl,
        "sac_state_dependence": policy_map_metrics,
        "representative_rollout_economic_performance": economic_performance,
        "training_any_constraint_violation_episode_rate": float(
            np.mean(log_arrays["violation_rate"][training_mask] > 0.0)
        ),
        "training_constraint_violation_step_rate": float(
            np.mean(log_arrays["violation_rate"][training_mask])
        ),
        "training_rpi_violation_step_rate": float(
            np.mean(log_arrays["rpi_violation_rate"][training_mask])
        ),
        "training_disturbance_bound_exceedance_step_rate": float(
            np.mean(log_arrays["disturbance_bound_exceedance_rate"][training_mask])
        ),
        "training_state_excess_squared_mean": float(
            np.mean(log_arrays["state_excess_squared_mean"][training_mask])
        ),
        "training_input_excess_squared_mean": float(
            np.mean(log_arrays["input_excess_squared_mean"][training_mask])
        ),
        "training_rpi_excess_squared_mean": float(
            np.mean(log_arrays["rpi_excess_squared_mean"][training_mask])
        ),
        "training_feasible_action_mapping_rate": float(
            np.mean(log_arrays["feasible_action_mapping_rate"][training_mask])
        ),
        "first_20_return_mean": float(np.mean(training_returns[:20])),
        "last_20_return_mean": float(np.mean(training_returns[-20:])),
        "reward_formula": (
            "(J_nominal_economic-J_current)/reward_cost_scale "
            "- lambda_qp*||v_qp-v_candidate||_2^2 "
            "- lambda_map*||v_safe_ray-v_requested||_2^2 "
            "- lambda_du*||delta_residual_executed||_2^2 "
            "- violation_event_penalties - normalized_hinge_excess_penalties"
        ),
        "economic_reward_form": (
            "linear_monotone_decreasing_in_observed_economic_stage_cost"
        ),
        "continuous_penalty_form": (
            "negative_weighted_squared_L2; state/input/RPI use normalized "
            "positive-part excess beyond their bounds"
        ),
        "event_penalty_form": (
            "fixed_nonnegative_penalty; squaring a Boolean indicator is identical"
        ),
        "reward_can_be_positive": True,
        "reward_sign_note": (
            "positive reward only means the observed stage cost improvement over "
            "the fixed nominal-economic baseline exceeds the nonnegative penalties; "
            "the economic action ordering remains unambiguous"
        ),
        "reward_reference": "fixed_nominal_economic_point_independent_of_terminal_center",
        "reward_reference_cost": nominal_economic_reference_cost,
        "economic_optimum_precomputed_for_sac": False,
        "reward_uses_observed_stage_cost": True,
        "economic_optimum_is_actor_observation": False,
        "safety_anchor_used_for_observation_centering": True,
        "feedback_control_law": feedback_law,
        "hinf_gamma_design": design.gamma_design,
        "hinf_norm_frequency_grid": design.gamma_sampled,
        "hinf_gain_parameterization": "continuous_direct_K_with_safety_gate",
        "hinf_state_weight_scale_selected": design.gain_state_weight_scale,
        "hinf_input_weight_scale_selected": design.gain_input_weight_scale,
        "hinf_gain_candidates_feasible": design.gain_candidates_feasible,
        "closed_loop_spectral_radius": float(
            np.max(np.abs(np.linalg.eigvals(design.a + design.b @ design.k)))
        ),
        "rpi_support_normalized": design.rpi_support.tolist(),
        "rpi_support_lower_normalized": design.rpi_support_lower.tolist(),
        "rpi_support_upper_normalized": design.rpi_support_upper.tolist(),
        "rpi_bounding_width_physical": (
            (design.rpi_support_lower + design.rpi_support_upper)
            * cfg.state_scale
        ).tolist(),
        "rpi_polygon_area_percent_kpa": rpi_area,
        "rpi_polygon_area_as_percent_of_X": float(
            100.0 * rpi_area / state_constraint_area
        ),
        "axis_aligned_box_rpi_width_physical_same_gain": (
            design.box_reference_rpi_width_physical.tolist()
        ),
        "axis_aligned_box_rpi_area_same_gain": (
            design.box_reference_rpi_area_physical
        ),
        "correlation_aware_rpi_area_reduction_percent": float(
            100.0 * (design.box_reference_rpi_area_physical - rpi_area)
            / max(design.box_reference_rpi_area_physical, 1e-12)
        ),
        "x_minus_z_width_physical": x_minus_z_width.tolist(),
        "x_minus_z_area_percent_kpa": float(np.prod(x_minus_z_width)),
        "x_minus_z_area_retention_percent_of_X": float(
            100.0 * np.prod(x_minus_z_width) / state_constraint_area
        ),
        "controlled_invariant_lower_physical": model.physical_state(
            design.invariant_lower
        ).tolist(),
        "controlled_invariant_upper_physical": model.physical_state(
            design.invariant_upper
        ).tolist(),
        "controlled_invariant_width_physical": invariant_width.tolist(),
        "controlled_invariant_area_percent_kpa": float(np.prod(invariant_width)),
        "controlled_invariant_homothetic_scale": design.invariant_scale,
        "safe_center_state": cfg.safe_center_state.tolist(),
        "safe_center_input": safe_center_input.tolist(),
        "safe_center_cost": safe_center_cost,
        "nominal_economic_reference_state": cfg.linearization_state.tolist(),
        "nominal_economic_reference_input": cfg.linearization_input.tolist(),
        "disturbance_box_normalized": design.w_bound.tolist(),
        "evaluation_peak_positive_effective_disturbance_normalized": (
            peak_w_positive.tolist()
        ),
        "evaluation_peak_negative_effective_disturbance_normalized": (
            peak_w_negative.tolist()
        ),
        "disturbance_bound_method": (
            "four-facet asymmetric W_theta={w|Mw<=m}; initial local corner/"
            "sample hull at the economic linearization point; observed "
            "state-transition residuals are audited without changing the fixed "
            "design in proposed mode"
        ),
        "disturbance_polytope_vertex_count": int(len(design.w_vertices)),
        "qp_intervention_tolerance_normalized": cfg.qp_intervention_tolerance,
        "reward_penalty_weights": {
            "projection_squared": cfg.projection_penalty_weight,
            "feasible_action_mapping_squared": (
                cfg.feasible_action_mapping_penalty_weight
            ),
            "input_move_squared": cfg.input_move_penalty_weight,
            "state_violation_event": cfg.state_violation_event_penalty,
            "input_violation_event": cfg.input_violation_event_penalty,
            "rpi_violation_event": cfg.rpi_violation_event_penalty,
            "qp_infeasible_event": cfg.qp_infeasible_event_penalty,
            "state_normalized_excess_squared": cfg.state_excess_square_weight,
            "input_normalized_excess_squared": cfg.input_excess_square_weight,
            "rpi_relative_excess_squared": cfg.rpi_excess_square_weight,
        },
        "actor_learning_rate": cfg.actor_learning_rate,
        "critic_learning_rate": cfg.critic_learning_rate,
        "entropy_learning_rate": cfg.entropy_learning_rate,
        "residual_action_scale_normalized": cfg.residual_action_scale.tolist(),
        "replay_action_execution_mask": (
            "one for the declared feasible-ray action mapping; zero only if the "
            "verification QP fails and its fallback replaces the action"
        ),
        "safe_action_parameterization": (
            "state-dependent ray from the feasible theta base to the boundary "
            "of the tightened-input and one-step invariant polytope"
        ),
        "input_move_penalty_scope": (
            "change in executed SAC residual only; excludes nominal and H-infinity motion"
        ),
        "warmup_update_order": (
            "use uniform random actions until warmup_steps while SAC updates begin "
            "as soon as replay contains one minibatch"
        ),
        "training_initial_radius_fraction": cfg.training_initial_radius_fraction,
        "alpha_floor": cfg.alpha_min,
        "entropy_tuning_warmup_updates": cfg.entropy_tuning_warmup_updates,
        "empirical_regret_definition": (
            "post-hoc normalized gap of best-so-far fixed-seed deterministic "
            "evaluation to the best evaluation observed in this run; it is "
            "not the training reward or a theoretical optimality certificate"
        ),
    }
    with (cfg.output_dir / "metrics.json").open("w", encoding="utf-8") as stream:
        json.dump(metrics, stream, indent=2, ensure_ascii=False)
    print(json.dumps(metrics, indent=2, ensure_ascii=False))
    close_all_plots()


if __name__ == "__main__":
    main()
